version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pgconf/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pgconf/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

  tracker:
    build: 
      context: .
      dockerfile: tracker/Dockerfile
    ports:
      - "5100:5100"
    env_file:
      - ${ENV_FILE}
    depends_on:
      - postgres

  matrix-song-bot:
    build: ./matrix-song-bot
    restart: always
    depends_on:
      - postgres
    env_file:
      - ${ENV_FILE}
    volumes:
      - ./matrix_session:/app/matrix_session

  genre-reader:
    build:
      context: .
      dockerfile: genre-reader/Dockerfile
    env_file:
      - ${ENV_FILE}
    depends_on:
      - postgres

  music-fetcher:
    build:
      context: .
      dockerfile: music-fetcher/Dockerfile
    env_file:
      - ${ENV_FILE}
    depends_on:
      - postgres
    volumes:
      - /music:/music
      - /import:/import

  music-librarian:
    build: 
      context: .
      dockerfile: music-librarian/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ${ENV_FILE}
    depends_on:
      - postgres
  
  youtube-reader:
    build: ./youtube-reader
    env_file:
      - ${ENV_FILE}
    depends_on:
      - postgres

volumes:
  pgdata:
    name: ${COMPOSE_PROJECT_NAME}_pgdata
