version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata-${ENVIRONMENT}:/var/lib/postgresql/data
      - ./db_init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pgconf/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pgconf/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

  tracker:
    build: ./tracker
    env_file:
      - ${ENV_FILE}
    depends_on:
      - postgres

  matrix-song-bot:
    build: ./matrix-song-bot
    restart: always
    depends_on:
      - postgres
    env_file:
      - ${ENV_FILE}
    volumes:
      - ./matrix_session:/app/matrix_session

  genre-reader:
    build: ./genre-reader
    env_file:
      - ${ENV_FILE}
    depends_on:
      - postgres
  
  youtube-reader:
    build: ./youtube-reader
    env_file:
      - ${ENV_FILE}
    depends_on:
      - postgres

volumes:
  pgdata-${ENVIRONMENT}:
