library: /import/beets/library.db
statefile: /import/beets/state.pickle
directory: /music

import:
  move: true
  write: true
  quiet_fallback: skip

plugins: fetchart embedart lastgenre

lastgenre:
  source: artist
  canonical: yes
  min_weight: 50
